name: Bug report
description: Something isn't working?
labels: []
assignees: []
type: Bug

body:
  - type: textarea
    id: bug-report
    attributes:
      label: Bug report
      placeholder: |
        Describe the bug and what happened.

        What was supposed to happen?

        Screenshots are always helpful!
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Include your operating system, distribution, terminal, multiplexer, and any other relevant details.
      placeholder: arch linux, ghostty, tmux, etc.
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      placeholder: v1.2.3 or 1b2c3d4
    validations:
      required: true
